# Generated by Django 4.1.12 on 2023-11-26 18:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCache',
            fields=[
                ('papername', models.CharField(max_length=255)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('text', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'comment_papers_db',
            },
        ),
    ]
