# Generated by Django 4.1.12 on 2023-11-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsCache',
            fields=[
                ('papername', models.CharField(max_length=255)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'comment_papers_db',
            },
        ),
        migrations.DeleteModel(
            name='CommentCache',
        ),
    ]
