# Generated by Django 4.1.12 on 2023-11-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentscache_delete_commentcache'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentscache',
            table='comment_db',
        ),
    ]
